### ISSUE TITLE
maintenance

### ISSUE THREAD

**Issue by darkmihai** [TrinityCore/aowow#1]
The website is currently closed for maintenance.
This will take a few minutes...

How i can fix, i make all sql update

**Comment by Sarjuuk** [comment]
My response is still the same. Your setup was interrupted at some point and needs to be continued using the same command.

**Comment by Kittnz** [comment]
I'v got the same problem here @Sarjuuk , i did php aowow --sql several times, it has errors in the end it said in the end.
