### ISSUE TITLE
Miss interpretation of negative ExclusiveGroup

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/aowow#10]
There's a miss interpretation of : if ExclusiveGroup < 0 on quest_template_addon
It doesn't mean "Closes Quests" but both quests must be rewarded to get access to the next quest
example: SELECT * FROM `quest_template_addon` WHERE id IN (12740, 12503);
here: https://woehead.way-of-elendil.fr/?quest=12503
Defend the Stand doesn't close access to Parachutes for the Argent Crusade.

**Comment by Sarjuuk** [comment]
so the correct interpretation would be:
Pa'Troll (12596) becomes available after Defend the Stand (12503) and Parachutes for the Argent Crusade (12740) are both completed?

**Comment by Killyana** [comment]
Yesn and this the case if the ExclusiveGroup < 0
In the case if ExclusiveGroup > 0 only one quest using this ExclusiveGroup  can be taken and rewarded so in this case "Closes Quests" is correct.

**Comment by Sarjuuk** [comment]
*probably* fixed in 57d4dc245907f15b0b65aa5298f7282589685753
