### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by Playon24** [TrinityCore/aowow#12]
After successfully installing and configuratin aowow the main page nor others wont load.

I keep receiving this error in the apache logs:
PHP Fatal error:  Can't inherit abstract function DbSimple_LastError::_logQuery() (previously declared abstract in DbSimple_Database) in /var/www/aowow/includes/libs/DbSimple/Database.php on line 95

After this nothing gets logged. If I reload the webpage the same error appears again.

**Comment by Sarjuuk** [comment]
congratulations, you found an unicorn.
you'll have to try 'n error this one.

start by commenting [this line](https://github.com/TrinityCore/aowow/blob/master/includes/libs/DbSimple/Database.php#L1275)

**Comment by Playon24** [comment]
Commented that line and got:
PHP Fatal error:  Cannot redeclare class DbSimple_Database in /var/www/aowow/includes/libs/DbSimple/Database.php on line 95

Sry for that, my php ver is: PHP 5.6.30-10+deb.sury.org~xenial+2 (cli)

**Comment by Sarjuuk** [comment]
except there is no redeclaration of that class happening, nor multiple inclusions.

are you by chance using some weird form of class auto-loader?

**Comment by Playon24** [comment]
What do you mean by "class auto-loader"? I have only basics php knowledge .

**Comment by Sarjuuk** [comment]
some form of script that includes files from the project for whatever reason.

i already include the db library manually, so it *might* cause a conflict if it'd include that file again.

but yeah, i'm out of ideas for now.

**Comment by Playon24** [comment]
I dont think i understood your statement but i dont use the aowows files for nothing else.

Clould it be something form the PHP modules?

There are the ones i use:
[PHP Modules]
calendar
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
XCache
XCache Cacher
XCache Coverager
XCache Optimizer
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
XCache
XCache Cacher
XCache Coverager
XCache Optimizer
Zend OPcache

**Comment by Sarjuuk** [comment]
*maybe* the XCache modules. The rest is unrelated or also enabled on my end.

On another note. This error occurs only if you try to display the actual web page. php uses two different configs for web and cli respectively. Maybe you can find something relevant there.

**Comment by Playon24** [comment]
XCache wast the problem.
Now i'm having troubble with icons dispaly.

**Comment by Sarjuuk** [comment]
Done a bit more reading. It may also be OPcache and XCache being in conflict with each other. But i cant test that.
I'll have to keep that issue in mind..

**Comment by Playon24** [comment]
Yes it is true. I reinstalled XCache module and disabled OPCache. So if one or anther is disabled the site works.
Do you know wich one is better?

**Comment by Sarjuuk** [comment]
no idea, never actively worked with OPcache and never new Xcache was a thinh.

hard to say what exactly you are missing.
icon files: `php aowow --build=simpleImg`
icon data structure `php aowow --sql=icons`
but other tables / generated files depend on those

**Comment by Playon24** [comment]
Thnak you. 
One last offtopic question then you can close the ticket.

In `aowow_dbverion` the column says `totemcategorycurrencies itemsquests` how can i sync those. I'v already tried `php aowow --sync=totemcategorycurrencies itemsquests` but nothing happens.

**Comment by Sarjuuk** [comment]
> totemcategorycurrencies

ugh . where did that mishap .. happen
There are some whitespaces missing. Format the field to `totemcategory currencies items quests` and do `php aowow --update`.

**Comment by Playon24** [comment]
Thank you for all your help.
