### ISSUE TITLE
Display objects, npcs, quests etc... which are in dungeon/raid/battleground

### ISSUE THREAD

**Issue by peycho** [TrinityCore/aowow#14]
Hello.

I have an issue with objects, npcs, quests which are located in dungeons or any other instance type.

How can I add this data?

I already used the options:
Calculate.Creature.Zone.Area.Data = 1
Calculate.Gameoject.Zone.Area.Data = 1

This however does not add the required locations of objects, npcs, quests.

What can I do?

**Comment by Sarjuuk** [comment]
Get a 403 client, merge maps, dungeonMap.dbc and WorldMapArea.dbc, run the setup again.

in short: you can't.

**Comment by peycho** [comment]
Thanks. I'll test it.

**Comment by Playon24** [comment]
Only 403 or other cata clients will work? For example 401 or 434

**Comment by Sarjuuk** [comment]
Will work in general, although multiple dungeon were revamped through the course of the expansion. Those maps won't fit onto the 335 dungeons.

**Comment by Playon24** [comment]
[ERR]   file setup/mpqdata/enUS/dbfilesclient/worldmaparea.dbc has incorrect magic bytes
[ERR]   cannot open file setup/mpqdata/enUS/dbfilesclient/worldmaparea.dbc
[ERR]   no suitable files found for worldmaparea.dbc, aborting.
[ERR]   SqlGen::generate() - required DBC worldmaparea.dbc not found!

**Comment by Sarjuuk** [comment]
or do it manually.
they are cached as dbc_* prefixed tables in the database before use.

**Comment by Playon24** [comment]
I dont understand.
I'v copyed dungeonMap.dbc and WorldMapArea.dbc from cata client, emptyed the dbc_dungeonmap, dbc_worldmaparea, dbc_worldmapoverlay, dbc_worldmaptransforms tables.

**Comment by Sarjuuk** [comment]
you have to .. manually .. case by case .. add the rows you want from the 403-dbcs into the dbc_* table you generated from 335-dbcs

**Comment by mazdafil** [comment]
Maybe you make an update that adds this feature?

**Comment by Sarjuuk** [comment]
No chance in hell!

Skim through the tickets here. Most are from people unable to handle the setup as is. What do you think will happen, if I add this. (even when it's optional)
