### ISSUE TITLE
File for localization ENUS not found.

### ISSUE THREAD

**Issue by jerbookins** [TrinityCore/aowow#16]
trying to install aowow from a fresh install

running aowow --firstrun returns the error:
File for localization ENUS not found.

**Comment by Sarjuuk** [comment]
Where have you put the files you got from the extraction step.

And on second thought. What locale **are** you using?

**Comment by jerbookins** [comment]
localization should be "enUS".

![image](https://user-images.githubusercontent.com/16745918/45407409-946d3e80-b626-11e8-9e30-fd28772e00f7.png)

**Comment by jackpoz** [comment]
worked fine for me, please check if the account can access the folder
