### ISSUE TITLE
Spell: Force Cast effect

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/aowow#17]
For spells that force cast a spell like: https://woehead.way-of-elendil.fr/?spell=67751

The spell that will be force casted on effect 3 is not displayed, it will be handful if it's shown like grow on effect 1

On spellwork the spell it displayed correctly:

Effect 2: Id 140 (SPELL_EFFECT_FORCE_CAST)
BasePoints = 1
Targets (38, 0) (TARGET_UNIT_NEARBY_ENTRY, NO_TARGET)
   Trigger spell (68642) Immunité : Entrave/Etourdir. Chance = 101
   Description: Dissipe tous les effets d'Entrave, de Renvoi des morts-vivants et d'étourdissement.

**Comment by Sarjuuk** [comment]
implemented in 0694367ee90262ed349c437af6424a499f37d90a

merge pending
