### ISSUE TITLE
Outdated creature_template structure.

### ISSUE THREAD

**Issue by HannibalRoG** [TrinityCore/aowow#18]
There is an old structure for the table. Npc names are shown as "npc not found" on the site.
![aowow](https://user-images.githubusercontent.com/19369492/64367996-a014fa80-d019-11e9-9e93-536934de1373.JPG)

**Comment by jackpoz** [comment]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=12440 seems to work fine
