### ISSUE TITLE
Spell effect Create Item display the wrong item name

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/aowow#25]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=40274
The displayed name is "Heavy Knothide Leather"  the last listed regent.

For other spell the item name is correct https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=19668

**Comment by jackpoz** [comment]
https://github.com/TrinityCore/aowow/commit/c2e2ea51f36800901a747b3aa5390f81a3e2daa5
