### ISSUE TITLE
Spell/Pet: Pets summoned by spells

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/aowow#28]
Can we get for spells that summon pets the same behavior as other summon effect, for example: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=46758 
Summon Pet: (26207) must display "Summon Pet: Loyal Boar" with Loyal Boar link to the npc
Also for the npc: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=26207 the spell https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=46758  must be displayed in the section summoned by

**Comment by Sarjuuk** [comment]
implemented in 3c088cd4e8342c1a8dd17025b68b857f53a28bbd

merge pending

**Comment by Killyana** [comment]
The npc don't display the spell used to summon it: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=26207#summoned-by

**Comment by Sarjuuk** [comment]
additional fix in 47458e3ec2ac14578df05977b15485fdd5035f88
