### ISSUE TITLE
Wrong text for SAI event

### ISSUE THREAD

**Issue by wodim** [TrinityCore/aowow#29]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=14353

Event #8 says "Summon Gordok Tribute for ?2", guess that ?2 should say something else.

**Comment by Killyana** [comment]
It's 2 hours the duration of the summon

**Comment by Sarjuuk** [comment]
Probably a typo. `%s2` as text variable.

**Comment by Sarjuuk** [comment]
typo fixed in 59ef124a2605aa436507688f0213050e62ebc851

that escalated quickly...
