### ISSUE TITLE
NPC missing from search

### ISSUE THREAD

**Issue by wodim** [TrinityCore/aowow#30]
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=travel+form

This should be part of the search results:

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=6573

**Comment by Killyana** [comment]
Every npc with a name containing parentheses will not appear in the search results.

**Comment by wodim** [comment]
Why?

**Comment by Killyana** [comment]
I don't know, it works fine for spells, items and gobs.

**Comment by Sarjuuk** [comment]
there are a lot of internal stuff hidden from searches for your default user. Mostly to provide results they are likely searching for.

If you grant yourself staff privileges in aowow these filters no longer apply.

**Comment by wodim** [comment]
I remember having heard this before in your own repo, and it makes no sense. If you intend to hide "internal stuff", that's a herculean task, something you simply can't do. And on top of that, hiding NPCs with parentheses in their names is just a dirty, half-assed approach.  Why not add an option somewhere so you can, you know, actually browse the database?

**Comment by Sarjuuk** [comment]
> Why not add an option somewhere so you can, you know, actually browse the database?

> If you grant yourself staff privileges in aowow these filters no longer apply.

**Comment by wodim** [comment]
But that requires me to install in on my server, etc. Guess that's what I'll eventually do, since it sadly is a policy here to have an artificially gimped database browser.
