### ISSUE TITLE
Spells not visible in search result

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/aowow#31]
This spell https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=50871 doesn't appear in: 
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=Savage+Rend

**Comment by leviathonbeast** [comment]
it does.

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?search=Savage+Rend#abilities

**Comment by Killyana** [comment]
50871?

**Comment by Sarjuuk** [comment]
08c98bc8eefeb49827e14a3d792179bf08c51ff5

spells with `attributes0 & 0x80` should now show up under 'uncategorized spell'
