### ISSUE TITLE
spell-group-stack not shows for some ranks

### ISSUE THREAD

**Issue by Faq** [TrinityCore/aowow#33]
Dont know how it should be, just reporting here.

Comparing some spells, noticed, that:
Arcane Brilliance Rank3
https://woehead.way-of-elendil.fr/?spell=43002#spell-group-stack has this tab
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=43002 but we dont

Arcane Brilliance Rank1, both have:
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=23028#spell-group-stack it is there
https://woehead.way-of-elendil.fr/?spell=23028#spell-group-stack

**Comment by Killyana** [comment]
https://woehead.way-of-elendil.fr is using 2 years old version of aowow, maybe something get broken since.

**Comment by Sarjuuk** [comment]
worksforme :shrug:

**Comment by Faq** [comment]
if no one else has this, just close.
