### ISSUE TITLE
Creature: Scourge Converter cannot be displayed

### ISSUE THREAD

**Issue by Killyana** [TrinityCore/aowow#35]
https://www.wowhead.com/npc=32257/scourge-converter

https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=32257

**Comment by Sarjuuk** [comment]
worksforme™

whats in the `aowow_errors` table

**Comment by Killyana** [comment]
I don't have access to that.

**Comment by Sarjuuk** [comment]
date|version|phpError|file|line|query|userGroups|message
---|----|----|----|----|----|---|----
1598802859|31|0|/home/sarjuuk/public_html/aowow/includes/smartAI.class.php|685|npc=32257|2|Call to undefined method Util::foramtTime()
you sure?

(at least i reproduced it^^)

**Comment by Sarjuuk** [comment]
fixed in 5179e6e09b3cc007735cb6dc70c76eb21d9db013
