### ISSUE TITLE
Extraction setup is unclear

### ISSUE THREAD

**Issue by ShinDarth** [TrinityCore/aowow#4]
Hello, I don't understand the step 5. of the installation guide. I have downloaded and compiled the MPQExtractor but then:

> .. for every locale you are going to use:
> <localeCode>/DBFilesClient/

it's not clear what <localeCode> is and how to extract what

**Comment by Sarjuuk** [comment]
https://gist.github.com/Sarjuuk/e171bf5e7e9f7503a779

give this a try

**Comment by Kittnz** [comment]
@ShinDarth i can help if you want, i had the same issues, i have to ask you another thing too so jump on IRC

**Comment by ShinDarth** [comment]
@Sarjuuk 


Extracting files...

Opening '/Users/Shin/WoW-335/Data/enUS/locale-enUS.MPQ'...

Searching for 'interface\calendar\holidays\*.blp'...
No file found!
./extract.sh: line 154: [: -eq: unary operator expected
[OK]  successfully extracted /Users/Shin/WoW-335/Data/enUS/locale-enUS.MPQ
Opening '/Users/Shin/WoW-335/Data/enUS/expansion-locale-enUS.MPQ'...

Searching for 'dbfilesclient\*.dbc'...
No file found!
Opening '/Users/Shin/WoW-335/Data/enUS/expansion-locale-enUS.MPQ'...

Searching for 'interface\worldmap\*.blp'...
No file found!
Opening '/Users/Shin/WoW-335/Data/enUS/expansion-locale-enUS.MPQ'...

Extracting files...

Failed to extract the file 'interface\framexml\globalstrings.lua' in /Applications/MAMP/htdocs/aowow/setup/mpqdata/enUS/interface/framexml/globalstrings.lua

**Comment by Kittnz** [comment]
you didn't extract everything and correctly, had the same issue

**Comment by Sarjuuk** [comment]
I've updated the gist. Apparently backslashes in single quoted strings are escape chars for you, but not for me.
also the unary operand error should be gone.

keep in mind, this is my first time with a bash script^^
