### ISSUE TITLE
error: SITE_HOST or STATIC_HOST not configured

### ISSUE THREAD

**Issue by peycho** [TrinityCore/aowow#5]
Hello.

I'm trying to setup a demo install from this project, but I have some undefined vars that are in database, but does not get detected by the web app.

Both variables are set with the php aowow 
force_ssl is disabled as well.
Maintenance is disabled too.

Any idea what can cause these variables, and maybe other to be undefined?
php aowow --firstrun complete with some warning about missing guids, but this should not be an issue.

**Comment by Sarjuuk** [comment]
I'll close this due to age. Should this still be relevant feel free to reopen it.
those variables should look something like
`SITE_HOST: example.com/aowow`
`STATIC_HOST: example.com/aowow/static`
or if you are fancy, an own address for the static content
