### ISSUE TITLE
[BUG] Spells

### ISSUE THREAD

**Issue by Kittnz** [TrinityCore/aowow#6]
Since tc implemented the new spell proc system, looking at spells is broken.
The table is gone.

```
DB ERROR:

Array
(
    [code] => 1146
    [message] => Table 'world.spell_proc_event' doesn't exist
    [query] => SELECT IF(ppmRate > 0, -ppmRate, customChance) AS chance, cooldown FROM spell_proc_event WHERE entry = 568
    [context] => E:\xampp\htdocs\wow\aowow\pages\spell.php line 1496
)
```

**Comment by Keader** [comment]
spell_proc_event ->  spell_proc now xd

**Comment by Kittnz** [comment]
table doesn't have the same rows etc
ppmRate, customChance is not in that table

**Comment by ariel-** [comment]
`ppmRate` changed to `ProcsPerMinute`
`customChance` changed to `Chance`
`cooldown` changed to `Cooldown`
