### ISSUE TITLE
[BUG] php aowow --sql

### ISSUE THREAD

**Issue by Kittnz** [TrinityCore/aowow#7]
Updating db --sql results in a few errors.

![afbeelding](https://cloud.githubusercontent.com/assets/5845231/22710578/1edb9da0-ed7e-11e6-995e-6ee6cce9c903.png)
![afbeelding](https://cloud.githubusercontent.com/assets/5845231/22710601/338bf6be-ed7e-11e6-949e-659d9db97596.png)

**Comment by Sarjuuk** [comment]
should be fixed, please recheck

**Comment by Kittnz** [comment]
Fixed
