### ISSUE TITLE
Spells: Spell Effects are not correct and faulty linking

### ISSUE THREAD

**Issue by Kittnz** [TrinityCore/aowow#8]
For example http://domain/aowow/?npc=16380
Here you can see what his abilitys are and what he drops. But you can't see who summoned him.

https://woehead.way-of-elendil.fr/?npc=16380#summoned-by
Here it has information that it is summoned by https://woehead.way-of-elendil.fr/?spell=28291

It seems Effect 1 is Jump: (16380) on aowow and the other has the right effect which is summon Summon: (Bone Witch) that this is correct.

**Comment by Sarjuuk** [comment]
In the TDB 335.62 release this serverside spell has effectId 41 for index 0.
according to [SpellEffects.cpp#L102](https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/game/Spells/SpellEffects.cpp#L102) it is indeed JUMP

**Comment by Kittnz** [comment]
Faulty install.
