### ISSUE TITLE
No Image 

### ISSUE THREAD

**Issue by darkmihai** [TrinityCore/aowow#9]
Aowow

Log in / Register|Feedback|Language
About us & contact|Language
ツ 2017 Aowow
rev. 22

 how i can fix. .....

**Comment by Aokromes** [comment]
If you mean item images:

Q: How can i get the modelviewer to work?
A: You can't anymore. Wowhead switched from Flash to WebGL (as they should) and moved or deleted the old files in the process.

**Comment by Sarjuuk** [comment]
what kind of images on what page..?

**Comment by darkmihai** [comment]
![eror](https://cloud.githubusercontent.com/assets/613540/23579672/85277c52-00fa-11e7-9b87-ea7227b01add.png)

Check

**Comment by Aokromes** [comment]
works for me (TM).

http://i.imgur.com/wljOhqt.jpg

**Comment by darkmihai** [comment]
any ideea how i can  fix ?

**Comment by Sarjuuk** [comment]
recheck if your server is allowed to write into static/
retry generating icons `php aowow --build=simpleImg,talentIcons --icons`

if your initial setup finished unexpectedly there is probably more things missing, then just icons

**Comment by darkmihai** [comment]
after i use the command i get this errors

https://paste.ofcode.org/D7mvG7cErb38jyhdq59Pkx

**Comment by Aokromes** [comment]
the problem is you miss those files, read installation guide.

**Comment by darkmihai** [comment]
same error Aokromes can you send me mpqdata ?
